name: Build My Android APK
on: [push, pull_request]

jobs:
  BuildAPK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: corepack enable

      - name: Install Dependencies
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: true

      - name: Build Android Release
        run: |
          cd packages/app-mobile/android
          chmod +x gradlew
          ./gradlew assembleRelease
