name: BUILD APK NEW Automatic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install

    - name: Build Android APK
      working-directory: packages/app-android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease
